const features={
    "GOLD": [
        {
            "_id": "64a3e6b7ed36f1bc45bf76aa",
            "id": "64a3e6b7ed36f1bc45bf76aa",
            "name": "featre 2",
            "status": "active",
            "createdAt": "2023-07-04T09:30:31.342Z",
            "category": {
                "_id": "64ad3ac7952398e75da67d86",
                "name": "GOLD",
                "catType": "Plan Features",
                "image": "",
                "icon": "",
                "banner": "",
                "altImageName": "",
                "altIconName": "",
                "bannerOverlayHeading": "",
                "order": 10,
                "featured": "No",
                "parentCategory": null,
                "subParentCategory": null,
                "status": "active",
                "urlKey": "",
                "metaTitle": "",
                "metaDescription": "",
                "keywords": "",
                "isDeleted": false,
                "createdAt": "2023-07-11T11:19:35.035Z",
                "updatedAt": "2023-07-12T13:41:03.928Z",
                "__v": 0,
                "bannerOverlayBody": "",
                "description": ""
            },
            "categoryName": "GOLD",
            "categoryId": "64ad3ac7952398e75da67d86",
            "isDeleted": false,
            "checked": true
        },
        {
            "_id": "64ad0270e5aa778d26a53e54",
            "id": "64ad0270e5aa778d26a53e54",
            "name": "sdf",
            "status": "active",
            "createdAt": "2023-07-11T07:19:12.322Z",
            "category": {
                "_id": "64ad3ac7952398e75da67d86",
                "name": "GOLD",
                "catType": "Plan Features",
                "image": "",
                "icon": "",
                "banner": "",
                "altImageName": "",
                "altIconName": "",
                "bannerOverlayHeading": "",
                "order": 10,
                "featured": "No",
                "parentCategory": null,
                "subParentCategory": null,
                "status": "active",
                "urlKey": "",
                "metaTitle": "",
                "metaDescription": "",
                "keywords": "",
                "isDeleted": false,
                "createdAt": "2023-07-11T11:19:35.035Z",
                "updatedAt": "2023-07-12T13:41:03.928Z",
                "__v": 0,
                "bannerOverlayBody": "",
                "description": ""
            },
            "categoryName": "GOLD",
            "checked":true,
            "categoryId": "64ad3ac7952398e75da67d86",
            "isDeleted": false
        },
      
    ],
    "new": [
        {
            "_id": "64a3e6beed36f1bc45bf76b1",
            "id": "64a3e6beed36f1bc45bf76b1",
            "name": "featue 3",
            "status": "active",
            "createdAt": "2023-07-04T09:30:38.442Z",
            "category": {
                "_id": "64ae546548af27954cf12e0c",
                "name": "new",
                "catType": "Plan Features",
                "image": "",
                "icon": "",
                "banner": "",
                "altImageName": "",
                "altIconName": "",
                "bannerOverlayHeading": "",
                "order": null,
                "featured": "No",
                "parentCategory": null,
                "subParentCategory": null,
                "status": "active",
                "urlKey": "",
                "metaTitle": "",
                "metaDescription": "",
                "keywords": "",
                "isDeleted": false,
                "createdAt": "2023-07-12T07:21:09.055Z",
                "updatedAt": "2023-07-12T13:40:02.259Z",
                "__v": 0,
                "bannerOverlayBody": "",
                "description": ""
            },
            "categoryName": "new",
            "categoryId": "64ae546548af27954cf12e0c",
            "isDeleted": false,
        },
        {
            "_id": "64a3de3ded36f1bc45bf7198",
            "id": "64a3de3ded36f1bc45bf7198",
            "name": "new feature",
            "status": "active",
            "createdAt": "2023-07-04T08:54:21.659Z",
            "category": {
                "_id": "64ae546548af27954cf12e0c",
                "name": "new",
                "catType": "Plan Features",
                "image": "",
                "icon": "",
                "banner": "",
                "altImageName": "",
                "altIconName": "",
                "bannerOverlayHeading": "",
                "order": null,
                "featured": "No",
                "parentCategory": null,
                "subParentCategory": null,
                "status": "active",
                "urlKey": "",
                "metaTitle": "",
                "metaDescription": "",
                "keywords": "",
                "isDeleted": false,
                "createdAt": "2023-07-12T07:21:09.055Z",
                "updatedAt": "2023-07-12T13:40:02.259Z",
                "__v": 0,
                "bannerOverlayBody": "",
                "description": ""
            },
            "categoryName": "new",
            "categoryId": "64ae546548af27954cf12e0c",
            "isDeleted": false
        }
    ]
}
const testModel={features}
export default testModel